mutation CreateBooking ($createBookingInput: CreateBookingInput!) {
  createBooking(createBookingInput: $createBookingInput) {
    id
  }
}

mutation PayBooking ($payBookingInput: PayBookingInput!) {
  payBooking(payBookingInput: $payBookingInput) {
    id
  }
}

query GetBookingById ($id: String!) {
  getBookingById(id: $id) {
    id
    travelId
    seats
    grandTotal
    createdAt
    expiredAt
    updatedAt
    status
    firstName
    lastName
    email
    phoneNumber
    address
    city
    province
    country
    zipCode
    paymentProcessor
    paymentId
  }
}

mutation DeleteBookingById ($id: String!) {
  deleteBookingById(id: $id) {
    id
  }
}

